apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-materials
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
