apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - importer-job.yaml
  - ingress.yaml

transformers:
  - common-labels.yaml