apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base application manifests shared across environments
resources:
  - ../../base

# The home cluster mirrors the DEV namespace layout on a separate runner/cluster.
namespace: campus-dev

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: auth-config
    envs:
      - config/auth-config.env

  - name: backend-config
    envs:
      - config/backend-config.env

  - name: importer-config
    envs:
      - config/importer-config.env

secretGenerator:
  - name: db-secrets
    envs:
      - secrets/db-secrets.env
    type: Opaque

  - name: auth-secrets
    envs:
      - secrets/auth-secrets.env
    type: Opaque

images:
  - name: campus-frontend
    newName: ghcr.io/nexoc/campus-frontend
    newTag: tag-change-me

  - name: campus-auth
    newName: ghcr.io/nexoc/campus-auth
    newTag: tag-change-me

  - name: campus-backend
    newName: ghcr.io/nexoc/campus-backend
    newTag: tag-change-me

  - name: campus-nginx
    newName: ghcr.io/nexoc/campus-nginx
    newTag: tag-change-me

  - name: campus-importer
    newName: ghcr.io/nexoc/campus-importer
    newTag: tag-change-me

patches:
  - path: replicas-patch.yaml
  - path: httproute-patch.yaml
  - path: envoyproxy-patch.yaml
  - path: namespace-patch.yaml
    target:
      version: v1
      kind: Namespace
      name: campus
